### 201 {}

POST http://localhost:5000/contacts
Content-Type: application/json

{
    "name": "Test",
    "telNumber": "+380123456780",
    "birthday": "1990-12-01"
}

### 422 Validation Error

POST  http://localhost:5000/contacts
Content-Type: application/json

{
    "name": "1",
    "telNumber": "+380123456780",
    "birthday": "1990-12-01"
}

### 200 []

GET http://localhost:5000/contacts?page=1&results=8

### 200 {}

GET http://localhost:5000/contacts/5 HTTP/1.1

### 404 Contact Not Found

GET http://localhost:5000/contacts/1000 HTTP/1.1

### 200 {}

PATCH http://localhost:5000/contacts/2
Content-Type: application/json

{
    "name": "NewName"
}

### 404 Contact Not Found

PATCH http://localhost:5000/contacts/1000
Content-Type: application/json

{
    "name": "NewName"
}

### 422 Validation Error

PATCH http://localhost:5000/contacts/1
Content-Type: application/json

{
    "name": "N"
}

### 204 

DELETE http://localhost:5000/contacts/1 HTTP/1.1

### 404 Contact Not Found

DELETE http://localhost:5000/contacts/1000 HTTP/1.1